prometheus

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -1,9 +1,10 @@
-name: Deploy Task Tracker to GCP VM
+name: Deploy Task Tracker to VM
 
 on:
   push:
     branches:
       - main
+      - staging
 
 jobs:
   update_code:
@@ -22,11 +23,28 @@ jobs:
           port: 22
           script: |
             set -x
-            cd ~/assessments || { echo "Directory ~/task-tracker not found!"; exit 1; }
+            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
+              cd ~/assessments-prod || { echo "Directory ~/assessments-prod not found!"; exit 1; }
+            elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
+              cd ~/assessments-staging || { echo "Directory ~/assessments-staging not found!"; exit 1; }
+            else
+              echo "Branch not deployable, skipping deployment."
+              exit 0
+            fi
+
             if [ ! -d .git ]; then
               echo "Error: Not a git repository!"
               exit 1
             fi
-            git pull origin main
+
+            git pull origin ${{ github.ref_name }}
+
+            # Stopping all services
             sudo docker compose down
+
+            # Rebuilding and starting all services including Prometheus and Grafana
             sudo docker compose up -d --build
+
+            # Optional: restart Prometheus and Grafana (if you need to force them)
+            sudo docker restart prometheus
+            sudo docker restart grafana
