deployment files

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -22,7 +22,7 @@ jobs:
           port: 22
           script: |
             set -x
-            cd ~/task-tracker || { echo "Directory ~/task-tracker not found!"; exit 1; }
+            cd ~/assessments || { echo "Directory ~/task-tracker not found!"; exit 1; }
             if [ ! -d .git ]; then
               echo "Error: Not a git repository!"
               exit 1
